export type InstructorCourse = {
  id: string;
  title: string;
  students: number;
  avgProgress: number;
  rating: number;
  status: "active" | "completed" | "draft";
  lastUpdated: string;
};

export const mockInstructorCourses: Record<string, InstructorCourse[]> = {
  "inst-1": [
    {
      id: "course-1",
      title: "React Fundamentals",
      students: 120,
      avgProgress: 75,
      rating: 4.7,
      status: "active",
      lastUpdated: "2024-04-10",
    },
    {
      id: "course-2",
      title: "Advanced React Patterns",
      students: 85,
      avgProgress: 62,
      rating: 4.8,
      status: "active",
      lastUpdated: "2024-04-12",
    },
    {
      id: "course-3",
      title: "Next.js Complete Guide",
      students: 95,
      avgProgress: 58,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-08",
    },
    {
      id: "course-4",
      title: "TypeScript Mastery",
      students: 110,
      avgProgress: 88,
      rating: 4.6,
      status: "completed",
      lastUpdated: "2024-03-25",
    },
    {
      id: "course-5",
      title: "React Native Basics",
      students: 40,
      avgProgress: 15,
      rating: 4.5,
      status: "draft",
      lastUpdated: "2024-04-15",
    },
  ],
  "inst-2": [
    {
      id: "course-6",
      title: "Python for Data Science",
      students: 150,
      avgProgress: 82,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-11",
    },
    {
      id: "course-7",
      title: "Machine Learning Basics",
      students: 95,
      avgProgress: 68,
      rating: 4.8,
      status: "active",
      lastUpdated: "2024-04-09",
    },
    {
      id: "course-8",
      title: "Deep Learning with TensorFlow",
      students: 75,
      avgProgress: 45,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-13",
    },
  ],
  "inst-3": [
    {
      id: "course-9",
      title: "Flutter Complete Course",
      students: 130,
      avgProgress: 70,
      rating: 4.7,
      status: "active",
      lastUpdated: "2024-04-10",
    },
    {
      id: "course-10",
      title: "iOS Development with Swift",
      students: 88,
      avgProgress: 55,
      rating: 4.6,
      status: "active",
      lastUpdated: "2024-04-12",
    },
    {
      id: "course-11",
      title: "Android Kotlin Masterclass",
      students: 102,
      avgProgress: 78,
      rating: 4.8,
      status: "active",
      lastUpdated: "2024-04-08",
    },
    {
      id: "course-12",
      title: "React Native Advanced",
      students: 65,
      avgProgress: 42,
      rating: 4.7,
      status: "active",
      lastUpdated: "2024-04-14",
    },
    {
      id: "course-13",
      title: "Mobile UI/UX Design",
      students: 95,
      avgProgress: 90,
      rating: 4.9,
      status: "completed",
      lastUpdated: "2024-03-30",
    },
  ],
  "inst-4": [
    {
      id: "course-14",
      title: "Docker & Kubernetes",
      students: 78,
      avgProgress: 65,
      rating: 4.6,
      status: "active",
      lastUpdated: "2024-04-11",
    },
    {
      id: "course-15",
      title: "AWS Cloud Practitioner",
      students: 92,
      avgProgress: 72,
      rating: 4.7,
      status: "active",
      lastUpdated: "2024-04-09",
    },
    {
      id: "course-16",
      title: "CI/CD with GitHub Actions",
      students: 40,
      avgProgress: 38,
      rating: 4.5,
      status: "active",
      lastUpdated: "2024-04-13",
    },
  ],
  "inst-5": [
    {
      id: "course-17",
      title: "UI/UX Design Fundamentals",
      students: 145,
      avgProgress: 85,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-10",
    },
    {
      id: "course-18",
      title: "Figma Masterclass",
      students: 120,
      avgProgress: 78,
      rating: 4.8,
      status: "active",
      lastUpdated: "2024-04-12",
    },
    {
      id: "course-19",
      title: "Design Systems",
      students: 65,
      avgProgress: 52,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-08",
    },
    {
      id: "course-20",
      title: "User Research Methods",
      students: 60,
      avgProgress: 95,
      rating: 4.7,
      status: "completed",
      lastUpdated: "2024-03-28",
    },
  ],
  "inst-6": [
    {
      id: "course-21",
      title: "Ethical Hacking Basics",
      students: 98,
      avgProgress: 68,
      rating: 4.8,
      status: "active",
      lastUpdated: "2024-04-11",
    },
    {
      id: "course-22",
      title: "Network Security",
      students: 82,
      avgProgress: 55,
      rating: 4.7,
      status: "active",
      lastUpdated: "2024-04-09",
    },
    {
      id: "course-23",
      title: "Penetration Testing",
      students: 70,
      avgProgress: 42,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-13",
    },
  ],
  "inst-8": [
    {
      id: "course-24",
      title: "Unity Game Development",
      students: 115,
      avgProgress: 72,
      rating: 4.8,
      status: "active",
      lastUpdated: "2024-04-10",
    },
    {
      id: "course-25",
      title: "Unreal Engine 5",
      students: 88,
      avgProgress: 58,
      rating: 4.7,
      status: "active",
      lastUpdated: "2024-04-12",
    },
    {
      id: "course-26",
      title: "Game Design Principles",
      students: 102,
      avgProgress: 80,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-08",
    },
    {
      id: "course-27",
      title: "2D Game Development",
      students: 95,
      avgProgress: 92,
      rating: 4.6,
      status: "completed",
      lastUpdated: "2024-03-20",
    },
  ],
  "inst-9": [
    {
      id: "course-28",
      title: "SQL Fundamentals",
      students: 125,
      avgProgress: 88,
      rating: 4.6,
      status: "active",
      lastUpdated: "2024-04-11",
    },
    {
      id: "course-29",
      title: "MongoDB Complete Guide",
      students: 65,
      avgProgress: 45,
      rating: 4.7,
      status: "active",
      lastUpdated: "2024-04-13",
    },
  ],
  "inst-10": [
    {
      id: "course-30",
      title: "Deep Learning Fundamentals",
      students: 140,
      avgProgress: 75,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-10",
    },
    {
      id: "course-31",
      title: "Neural Networks",
      students: 105,
      avgProgress: 62,
      rating: 4.8,
      status: "active",
      lastUpdated: "2024-04-12",
    },
    {
      id: "course-32",
      title: "Computer Vision",
      students: 88,
      avgProgress: 58,
      rating: 4.9,
      status: "active",
      lastUpdated: "2024-04-08",
    },
    {
      id: "course-33",
      title: "Natural Language Processing",
      students: 92,
      avgProgress: 48,
      rating: 4.8,
      status: "active",
      lastUpdated: "2024-04-14",
    },
  ],
};
